window.destinationData = [
  {
    slug: "grand-caucasus",
    name: "Grand Caucasus Tour",
    tagline: "Azerbaijan, Georgia, and Armenia in one premium 10 Days / 9 Nights group journey.",
    image: "assets/destination-banners/georgia-gergeti.png",
    packages: [
      {
        slug: "grand-caucasus-tour",
        title: "Grand Caucasus Tour",
        duration: "10 Days / 9 Nights",
        price: "From USD 1,153 per person",
        image: "assets/destination-banners/georgia-gergeti.png",
        summary: "A premium three-country Caucasus route with Baku, Gabala, Tbilisi, Kazbegi, Gudauri, Yerevan, Lake Sevan, Garni, Geghard, and Khor Virap.",
        highlights: [
          "Azerbaijan icons: Flame Towers, Heydar Aliyev Center, Old City Baku, Baku Boulevard, and Gabala",
          "Georgia icons: Old Tbilisi, Narikala cable car, Gudauri, Kazbegi, and Gergeti Trinity Church",
          "Armenia icons: Lake Sevan, Cascade Complex, Republic Square, Garni, Geghard, and Khor Virap",
          "Three countries with planned border assistance and private AC transport",
          "Premium dinners, professional local guides, and handpicked 4-star hotels",
        ],
        includes: [
          "9 nights accommodation in selected 4-star hotels",
          "Daily breakfast and 9 premium dinners",
          "Private AC coach or van as per group size",
          "Professional English-speaking guides in all destinations",
          "Airport transfers and intercity transfers as per itinerary",
          "Gergeti 4x4 transfer, Tbilisi cable car, and Georgian folk show dinner",
        ],
        pricing: [
          "Double sharing: USD 1,153 per person",
          "Triple sharing: USD 1,185 per person",
          "Single sharing: USD 1,493 per person",
        ],
        itinerary: [
          {
            day: "Day 1",
            title: "Arrival in Baku",
            image: "assets/destination-banners/azerbaijan-baku-bay.png",
            details: "Arrival assistance at Baku airport, private transfer to hotel, check-in, and relaxed evening on Baku Boulevard with dinner.",
          },
          {
            day: "Day 2",
            title: "Old City Baku, Flame Towers, and Heydar Aliyev Center",
            image: "assets/destination-banners/azerbaijan-collage.png",
            details: "Explore Icherisheher, Maiden Tower, Shirvanshah Palace area, Highland Park, Flame Towers photo stop, and the flowing architecture of Heydar Aliyev Center.",
          },
          {
            day: "Day 3",
            title: "Gobustan, Mud Volcanoes, and Gabala",
            image: "assets/destination-banners/azerbaijan-flame-towers.png",
            details: "Visit Gobustan rock art landscape, mud volcano region when accessible, then continue toward Gabala for mountain scenery and overnight stay.",
          },
          {
            day: "Day 4",
            title: "Gabala to Tbilisi",
            image: "assets/destination-banners/georgia-gudauri.png",
            details: "Morning nature stops in Gabala, then scenic transfer toward Georgia with border assistance. Arrive in Tbilisi for dinner and overnight.",
          },
          {
            day: "Day 5",
            title: "Old Tbilisi and Georgian Folk Evening",
            image: "assets/georgia-packages/best-of-georgia-5n-6d/image-04.jpeg",
            details: "Discover Old Tbilisi, Metekhi, Sulfur Bath District, Bridge of Peace, Narikala cable car, Rustaveli Avenue, and an evening folk show dinner.",
          },
          {
            day: "Day 6",
            title: "Gudauri, Kazbegi, and Gergeti Trinity Church",
            image: "assets/destination-banners/georgia-gergeti.png",
            details: "Travel through Ananuri and Gudauri, stop at the Friendship Monument, continue to Kazbegi, and ride 4x4 vehicles to Gergeti Trinity Church.",
          },
          {
            day: "Day 7",
            title: "Mtskheta and Transfer to Armenia",
            image: "assets/georgia-packages/discover-georgia-9-nights-10-days/image-22.jpeg",
            details: "Visit Mtskheta, Jvari Monastery, and Svetitskhoveli Cathedral before crossing toward Armenia and arriving in Yerevan.",
          },
          {
            day: "Day 8",
            title: "Yerevan City, Cascade Complex, and Republic Square",
            image: "assets/main-caucasus-package/image-37.png",
            details: "Enjoy Yerevan highlights including Cascade Complex, Republic Square, Vernissage market area, and panoramic city viewpoints.",
          },
          {
            day: "Day 9",
            title: "Lake Sevan, Garni, Geghard, and Khor Virap",
            image: "assets/main-caucasus-package/image-42.png",
            details: "Experience Armenia's signature landscapes and heritage with Lake Sevan, Garni Temple, Geghard Monastery, and Khor Virap views toward Mount Ararat.",
          },
          {
            day: "Day 10",
            title: "Departure from Yerevan",
            image: "assets/main-caucasus-package/image-28.png",
            details: "Breakfast, check-out, free time subject to flight schedule, and private transfer to Yerevan airport.",
          },
        ],
        gallery: [
          "assets/destination-banners/azerbaijan-baku-bay.png",
          "assets/destination-banners/azerbaijan-collage.png",
          "assets/destination-banners/georgia-gergeti.png",
          "assets/destination-banners/georgia-gudauri.png",
          "assets/main-caucasus-package/image-37.png",
          "assets/main-caucasus-package/image-42.png",
        ],
      },
    ],
    places: [
      { name: "Azerbaijan", note: "Flame Towers, Heydar Aliyev Center, Old City Baku, Gobustan, and Gabala." },
      { name: "Georgia", note: "Gergeti Trinity Church, Old Tbilisi, Gudauri, Kazbegi, and Mtskheta." },
      { name: "Armenia", note: "Lake Sevan, Cascade Complex, Garni, Geghard, Yerevan, and Khor Virap." },
      { name: "Caucasus Route", note: "A smooth three-country itinerary built for group departures and premium FIT requests." },
    ],
    hotels: [],
  },
  {
    slug: "azerbaijan",
    name: "Azerbaijan",
    tagline: "Baku city breaks, Gabala nature stays, and winter escapes.",
    image: "assets/destination-banners/azerbaijan-baku-bay.png",
    packages: [
      {
        slug: "baku-gabala-escape",
        title: "Baku & Gabala Escape",
        duration: "4 Nights / 5 Days",
        price: "On request",
        image: "assets/destination-banners/azerbaijan-collage.png",
        summary: "A polished Azerbaijan program covering Baku's futuristic skyline, Old City heritage, Heydar Aliyev Center, Gobustan, and Gabala nature.",
        highlights: [
          "Flame Towers and Highland Park skyline views",
          "Heydar Aliyev Center exterior photo stop",
          "Old City Baku with Maiden Tower area and local cafes",
          "Gabala mountain scenery, cable car options, and family resort time",
        ],
        includes: [
          "Hotel accommodation with daily breakfast",
          "Airport transfers",
          "Private transport for sightseeing",
          "Professional driver or guide as per final quote",
        ],
        itinerary: [
          {
            day: "Day 1",
            title: "Arrival in Baku",
            image: "assets/destination-banners/azerbaijan-baku-bay.png",
            details: "Airport meet and greet, hotel transfer, check-in, and evening at Baku Boulevard.",
          },
          {
            day: "Day 2",
            title: "Old City, Flame Towers, and Heydar Aliyev Center",
            image: "assets/destination-banners/azerbaijan-collage.png",
            details: "Visit Old City Baku, Highland Park, Flame Towers viewpoint, and Heydar Aliyev Center.",
          },
          {
            day: "Day 3",
            title: "Gobustan and Absheron",
            image: "assets/destination-banners/azerbaijan-flame-towers.png",
            details: "Explore Gobustan rock art region, mud volcano landscape when accessible, and Absheron Peninsula highlights.",
          },
          {
            day: "Day 4",
            title: "Gabala Nature Day",
            image: "assets/destination-banners/azerbaijan-baku-bay.png",
            details: "Full-day Gabala visit with mountain views, cable car options, lake stops, and resort-style leisure time.",
          },
          {
            day: "Day 5",
            title: "Departure",
            image: "assets/destination-banners/azerbaijan-collage.png",
            details: "Breakfast, check-out, and private airport transfer.",
          },
        ],
        gallery: [
          "assets/destination-banners/azerbaijan-baku-bay.png",
          "assets/destination-banners/azerbaijan-collage.png",
          "assets/destination-banners/azerbaijan-flame-towers.png",
        ],
      },
    ],
    places: [
      { name: "Baku Old City", note: "Heritage lanes, Maiden Tower, cafes, and evening walks." },
      { name: "Flame Towers", note: "Modern skyline views and night photography." },
      { name: "Gabala", note: "Mountain scenery, cable cars, waterfalls, and family resorts." },
      { name: "Gobustan", note: "Mud volcanoes and ancient rock carvings." },
    ],
    hotels: [
      { name: "Park Inn by Radisson Baku", area: "Baku Boulevard", rating: 4, net: 360, image: "https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=900&q=80" },
      { name: "Shah Palace Hotel", area: "Old City", rating: 4, net: 310, image: "https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?auto=format&fit=crop&w=900&q=80" },
      { name: "Qafqaz Riverside Resort", area: "Gabala", rating: 5, net: 520, image: "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?auto=format&fit=crop&w=900&q=80" },
    ],
  },
  {
    slug: "georgia",
    name: "Georgia",
    tagline: "Tbilisi, Gudauri, Kazbegi, wine tours, and family holidays.",
    image: "assets/destination-banners/georgia-gergeti.png",
    packages: [
      {
        title: "Best of Georgia",
        duration: "5 Nights / 6 Days",
        price: "From USD 440 per person",
        image: "assets/georgia-packages/best-of-georgia-5n-6d/image-04.jpeg",
        document: "updated-documents/BEST OF GEORGIA_5 Nights 6 Days_Itinerary.docx",
        summary: "A private Georgia route combining Tbilisi, Kazbegi and Gudauri, Martvili Canyon, Batumi, and the UNESCO heritage city of Mtskheta.",
        highlights: [
          "Old Tbilisi walking tour with cable car ride to Narikala Fortress",
          "Kazbegi and Gudauri mountain tour with Gergeti Trinity Church 4x4 transfer",
          "Martvili Canyon boat ride and scenic Western Georgia landscapes",
          "Batumi city tour with Europe Square, Piazza Square, Ali & Nino Statue, and Alphabet Tower",
          "Mtskheta UNESCO tour with Jvari Monastery and Svetitskhoveli Cathedral",
        ],
        includes: [
          "Airport arrival and departure transfers",
          "3 nights accommodation in Tbilisi and 2 nights accommodation in Batumi",
          "Daily breakfast",
          "Private transportation throughout the tour",
          "Professional English-speaking driver",
          "Tbilisi cable car ticket, Gergeti 4x4 transfer, and Martvili Canyon boat ride",
        ],
        itinerary: [
          "Day 1: Arrival in Tbilisi and Old Tbilisi walking tour",
          "Day 2: Ananuri, Gudauri, Kazbegi mountain tour, and Gergeti Trinity Church",
          "Day 3: Tbilisi to Batumi via Martvili Canyon",
          "Day 4: Batumi city tour",
          "Day 5: Mtskheta tour and return to Tbilisi",
          "Day 6: Breakfast, check-out, and departure transfer",
        ],
        gallery: [
          "assets/georgia-packages/best-of-georgia-5n-6d/image-01.png",
          "assets/georgia-packages/best-of-georgia-5n-6d/image-02.jpeg",
          "assets/georgia-packages/best-of-georgia-5n-6d/image-03.jpeg",
          "assets/georgia-packages/best-of-georgia-5n-6d/image-04.jpeg",
          "assets/georgia-packages/best-of-georgia-5n-6d/image-05.jpeg",
          "assets/georgia-packages/best-of-georgia-5n-6d/image-06.jpeg",
          "assets/georgia-packages/best-of-georgia-5n-6d/image-07.jpeg",
          "assets/georgia-packages/best-of-georgia-5n-6d/image-08.jpeg",
          "assets/georgia-packages/best-of-georgia-5n-6d/image-09.jpeg",
          "assets/georgia-packages/best-of-georgia-5n-6d/image-10.png",
          "assets/georgia-packages/best-of-georgia-5n-6d/image-11.jpeg",
          "assets/georgia-packages/best-of-georgia-5n-6d/image-12.png",
          "assets/georgia-packages/best-of-georgia-5n-6d/image-13.jpeg",
          "assets/georgia-packages/best-of-georgia-5n-6d/image-14.jpeg",
        ],
      },
      {
        title: "Short Break of Georgia",
        duration: "2 Nights / 3 Days",
        price: "From USD 166 per person",
        image: "assets/georgia-packages/short-break-of-georgia-2n-3-days/image-08.jpeg",
        summary: "A compact Tbilisi and Caucasus mountain escape with Old Tbilisi, Narikala, Ananuri, Gudauri, Kazbegi, and airport transfers.",
        highlights: [
          "Old Tbilisi walking tour with cable car to Narikala Fortress",
          "Peace Bridge, Mother of Georgia, Sulfur Bath District, Rustaveli Avenue, and Liberty Square",
          "Full-day Ananuri, Gudauri, Kazbegi, and Gergeti Trinity Church mountain tour",
          "Group or private sightseeing options with 3-star and 4-star hotel choices",
        ],
        includes: [
          "2 nights hotel accommodation with daily breakfast",
          "Arrival and departure airport transfers",
          "Old Tbilisi walking tour with cable car ride",
          "Kazbegi and Gudauri full-day tour",
          "Transportation throughout the tour",
        ],
        itinerary: [
          "Day 1: Arrival in Tbilisi and Old Tbilisi walking experience",
          "Day 2: Ananuri, Gudauri, Kazbegi, and Gergeti Trinity Church mountain tour",
          "Day 3: Breakfast, hotel check-out, and airport departure transfer",
        ],
        gallery: [
          "assets/georgia-packages/short-break-of-georgia-2n-3-days/image-01.jpeg",
          "assets/georgia-packages/short-break-of-georgia-2n-3-days/image-02.jpeg",
          "assets/georgia-packages/short-break-of-georgia-2n-3-days/image-03.jpeg",
          "assets/georgia-packages/short-break-of-georgia-2n-3-days/image-04.jpeg",
          "assets/georgia-packages/short-break-of-georgia-2n-3-days/image-05.jpeg",
          "assets/georgia-packages/short-break-of-georgia-2n-3-days/image-06.jpeg",
          "assets/georgia-packages/short-break-of-georgia-2n-3-days/image-07.jpeg",
          "assets/georgia-packages/short-break-of-georgia-2n-3-days/image-08.jpeg",
        ],
      },
      {
        title: "Georgia Summer Escape",
        duration: "3 Nights / 4 Days",
        price: "From USD 818 per adult with flights",
        image: "assets/georgia-packages/georgia-summer-escape-3n-4-day-with-flight/image-01.jpeg",
        summary: "A guaranteed-departure UAE resident package with international flights, 4-star Tbilisi stay, guided city touring, and a Kazbegi mountain day.",
        highlights: [
          "International flights from Dubai, Sharjah, or Abu Dhabi included",
          "4-star hotel accommodation with daily breakfast",
          "Guided Tbilisi city tour with Chronicles of Georgia",
          "Ananuri, Gudauri, Kazbegi, and Gergeti Trinity Church 4x4 shuttle included",
        ],
        includes: [
          "International flight tickets from the UAE",
          "3 nights 4-star hotel accommodation in Tbilisi",
          "Daily breakfast and airport transfers",
          "Professional English-speaking guide",
          "Comfortable transportation throughout",
        ],
        itinerary: [
          "Day 1: Arrival in Tbilisi, city tour, Narikala cable car, and Chronicles of Georgia",
          "Day 2: Jinvali, Ananuri, Gudauri, Friendship Monument, Kazbegi, and Gergeti Trinity Church",
          "Day 3: Free day in Tbilisi or optional Kakheti and Sighnaghi tour",
          "Day 4: Breakfast, check-out, free time, and departure transfer",
        ],
        gallery: [
          "assets/georgia-packages/georgia-summer-escape-3n-4-day-with-flight/image-01.jpeg",
          "assets/georgia-packages/georgia-summer-escape-3n-4-day-with-flight/image-02.jpeg",
          "assets/georgia-packages/georgia-summer-escape-3n-4-day-with-flight/image-03.jpeg",
          "assets/georgia-packages/georgia-summer-escape-3n-4-day-with-flight/image-04.jpeg",
          "assets/georgia-packages/georgia-summer-escape-3n-4-day-with-flight/image-05.jpeg",
          "assets/georgia-packages/georgia-summer-escape-3n-4-day-with-flight/image-06.jpeg",
          "assets/georgia-packages/georgia-summer-escape-3n-4-day-with-flight/image-07.jpeg",
          "assets/georgia-packages/georgia-summer-escape-3n-4-day-with-flight/image-08.jpeg",
          "assets/georgia-packages/georgia-summer-escape-3n-4-day-with-flight/image-09.jpeg",
          "assets/georgia-packages/georgia-summer-escape-3n-4-day-with-flight/image-10.jpeg",
          "assets/georgia-packages/georgia-summer-escape-3n-4-day-with-flight/image-11.jpeg",
          "assets/georgia-packages/georgia-summer-escape-3n-4-day-with-flight/image-12.jpeg",
          "assets/georgia-packages/georgia-summer-escape-3n-4-day-with-flight/image-13.jpeg",
          "assets/georgia-packages/georgia-summer-escape-3n-4-day-with-flight/image-14.jpeg",
          "assets/georgia-packages/georgia-summer-escape-3n-4-day-with-flight/image-15.jpeg",
          "assets/georgia-packages/georgia-summer-escape-3n-4-day-with-flight/image-16.jpeg",
        ],
      },
      {
        title: "Discover Georgia",
        duration: "8 Nights / 9 Days",
        price: "From USD 694 per person",
        image: "assets/georgia-packages/discover-georgia-9-nights-10-days/image-23.jpeg",
        summary: "A deeper Georgia journey across Tbilisi, Kakheti, Kazbegi, Kutaisi, Martvili Canyon, Batumi, and Mtskheta on private transfers and sightseeing.",
        highlights: [
          "Old Tbilisi, Narikala Fortress, Peace Bridge, Mother of Georgia, and Chronicles of Georgia",
          "Kakheti wine region with wine tasting, bread-making, and Churchkhela masterclass",
          "Gergeti Trinity Church 4x4 excursion and Caucasus mountain scenery",
          "Prometheus Cave, Martvili Canyon, Batumi Boulevard, Botanical Garden, and Mtskheta",
        ],
        includes: [
          "Private airport arrival and departure transfers",
          "4 nights in Tbilisi, 1 night in Kazbegi, 1 night in Kutaisi, and 2 nights in Batumi",
          "Daily breakfast at 3-star or 4-star hotel options",
          "Private transfers and sightseeing as per itinerary",
          "Entrance included for Prometheus Cave and Martvili Canyon experiences",
        ],
        itinerary: [
          "Day 1: Arrival in Tbilisi",
          "Day 2: Full-day Old Tbilisi city tour",
          "Day 3: Kakheti and Sighnaghi wine region tour",
          "Day 4: Tbilisi to Kazbegi via Gudauri and Ananuri",
          "Day 5: Kazbegi to Kutaisi with Prometheus Cave and Bagrati Cathedral",
          "Day 6: Martvili Canyon and transfer to Batumi",
          "Day 7: Batumi city tour and Botanical Garden",
          "Day 8: Batumi to Tbilisi via Mtskheta",
          "Day 9: Departure from Tbilisi",
        ],
        gallery: [
          "assets/georgia-packages/discover-georgia-9-nights-10-days/image-01.jpeg",
          "assets/georgia-packages/discover-georgia-9-nights-10-days/image-02.jpeg",
          "assets/georgia-packages/discover-georgia-9-nights-10-days/image-03.jpeg",
          "assets/georgia-packages/discover-georgia-9-nights-10-days/image-04.jpeg",
          "assets/georgia-packages/discover-georgia-9-nights-10-days/image-05.jpeg",
          "assets/georgia-packages/discover-georgia-9-nights-10-days/image-06.jpeg",
          "assets/georgia-packages/discover-georgia-9-nights-10-days/image-07.jpeg",
          "assets/georgia-packages/discover-georgia-9-nights-10-days/image-08.jpeg",
          "assets/georgia-packages/discover-georgia-9-nights-10-days/image-09.jpeg",
          "assets/georgia-packages/discover-georgia-9-nights-10-days/image-10.jpeg",
          "assets/georgia-packages/discover-georgia-9-nights-10-days/image-11.jpeg",
          "assets/georgia-packages/discover-georgia-9-nights-10-days/image-12.jpeg",
          "assets/georgia-packages/discover-georgia-9-nights-10-days/image-13.jpeg",
          "assets/georgia-packages/discover-georgia-9-nights-10-days/image-14.jpeg",
          "assets/georgia-packages/discover-georgia-9-nights-10-days/image-15.jpeg",
          "assets/georgia-packages/discover-georgia-9-nights-10-days/image-16.jpeg",
          "assets/georgia-packages/discover-georgia-9-nights-10-days/image-17.jpeg",
          "assets/georgia-packages/discover-georgia-9-nights-10-days/image-18.jpeg",
          "assets/georgia-packages/discover-georgia-9-nights-10-days/image-19.jpeg",
          "assets/georgia-packages/discover-georgia-9-nights-10-days/image-20.jpeg",
          "assets/georgia-packages/discover-georgia-9-nights-10-days/image-21.jpeg",
          "assets/georgia-packages/discover-georgia-9-nights-10-days/image-22.jpeg",
          "assets/georgia-packages/discover-georgia-9-nights-10-days/image-23.jpeg",
        ],
      },
    ],
    places: [
      { name: "Tbilisi Old Town", note: "Sulphur baths, cable car, Narikala Fortress, and restaurants." },
      { name: "Gudauri", note: "Ski stays, mountain activities, and scenic viewpoints." },
      { name: "Kazbegi", note: "Gergeti Trinity Church and Caucasus mountain drives." },
      { name: "Kakheti", note: "Wine region, local dining, and countryside resorts." },
    ],
    hotels: [
      { name: "Ibis Styles Tbilisi Center", area: "Freedom Square", rating: 4, net: 330, image: "https://images.unsplash.com/photo-1564501049412-61c2a3083791?auto=format&fit=crop&w=900&q=80" },
      { name: "Rooms Hotel Tbilisi", area: "Vera", rating: 4, net: 590, image: "https://images.unsplash.com/photo-1590490360182-c33d57733427?auto=format&fit=crop&w=900&q=80" },
      { name: "Gudauri Lodge", area: "Gudauri", rating: 5, net: 680, image: "https://images.unsplash.com/photo-1578683010236-d716f9a3f461?auto=format&fit=crop&w=900&q=80" },
    ],
  },
  {
    slug: "armenia",
    name: "Armenia",
    tagline: "Yerevan culture, mountain monasteries, lakes, and heritage tours.",
    image: "assets/main-caucasus-package/image-37.png",
    packages: [
      {
        slug: "yerevan-sevan-heritage",
        title: "Yerevan, Lake Sevan & Heritage Trail",
        duration: "4 Nights / 5 Days",
        price: "On request",
        image: "assets/main-caucasus-package/image-37.png",
        summary: "A scenic Armenia itinerary focused on Yerevan, Cascade Complex, Lake Sevan, Garni Temple, Geghard Monastery, and Khor Virap.",
        highlights: [
          "Yerevan city tour with Cascade Complex and Republic Square",
          "Lake Sevan viewpoints and Sevanavank monastery area",
          "Garni Temple and Geghard Monastery heritage route",
          "Khor Virap with Mount Ararat photo opportunities",
        ],
        includes: [
          "Hotel accommodation with daily breakfast",
          "Airport transfers",
          "Private transport for sightseeing",
          "Professional driver or guide as per final quote",
        ],
        itinerary: [
          {
            day: "Day 1",
            title: "Arrival in Yerevan",
            image: "assets/main-caucasus-package/image-37.png",
            details: "Airport arrival, private transfer to hotel, check-in, and relaxed evening around Republic Square.",
          },
          {
            day: "Day 2",
            title: "Yerevan City and Cascade Complex",
            image: "assets/main-caucasus-package/image-28.png",
            details: "Discover Cascade Complex, Republic Square, Vernissage market area, city viewpoints, and local dining streets.",
          },
          {
            day: "Day 3",
            title: "Lake Sevan",
            image: "assets/main-caucasus-package/image-42.png",
            details: "Full-day Lake Sevan route with blue-water viewpoints, Sevanavank area, and relaxed lakeside stops.",
          },
          {
            day: "Day 4",
            title: "Garni, Geghard, and Khor Virap",
            image: "assets/main-caucasus-package/image-29.png",
            details: "Visit Garni Temple, Geghard Monastery, and Khor Virap for one of Armenia's most iconic Mount Ararat views.",
          },
          {
            day: "Day 5",
            title: "Departure",
            image: "assets/main-caucasus-package/image-37.png",
            details: "Breakfast, check-out, and private transfer to Yerevan airport.",
          },
        ],
        gallery: [
          "assets/main-caucasus-package/image-37.png",
          "assets/main-caucasus-package/image-42.png",
          "assets/main-caucasus-package/image-28.png",
          "assets/main-caucasus-package/image-29.png",
        ],
      },
    ],
    places: [
      { name: "Yerevan Cascade", note: "City views, museums, cafes, and evening walks." },
      { name: "Garni Temple", note: "Classical ruins and canyon scenery." },
      { name: "Geghard Monastery", note: "Historic monastery carved into mountain rock." },
      { name: "Lake Sevan", note: "Blue-water views, fish restaurants, and relaxed day trips." },
    ],
    hotels: [
      { name: "Ani Grand Hotel Yerevan", area: "Yerevan Center", rating: 4, net: 350, image: "https://images.unsplash.com/photo-1582719508461-905c673771fd?auto=format&fit=crop&w=900&q=80" },
      { name: "Ramada Hotel & Suites Yerevan", area: "Republic Square", rating: 4, net: 430, image: "https://images.unsplash.com/photo-1568084680786-a84f91d1153c?auto=format&fit=crop&w=900&q=80" },
      { name: "Tufenkian Historic Yerevan", area: "Vernissage", rating: 4, net: 470, image: "https://images.unsplash.com/photo-1571896349842-33c89424de2d?auto=format&fit=crop&w=900&q=80" },
    ],
  },
  {
    slug: "dubai",
    name: "Dubai",
    tagline: "City hotels, desert safari, theme parks, cruises, and transfers.",
    image: "https://images.unsplash.com/photo-1512453979798-5ea266f8880c?auto=format&fit=crop&w=1600&q=85",
    places: [
      { name: "Burj Khalifa", note: "Observation deck, Dubai Mall, fountains, and skyline photos." },
      { name: "Desert Safari", note: "Dune bashing, BBQ dinner, shows, and private transfers." },
      { name: "Dubai Marina", note: "Dhow cruise, waterfront dining, and beach access." },
      { name: "Museum of the Future", note: "Iconic architecture and futuristic exhibits." },
    ],
    hotels: [
      { name: "Rove Downtown Dubai", area: "Downtown", rating: 3, net: 410, image: "https://images.unsplash.com/photo-1584132967334-10e028bd69f7?auto=format&fit=crop&w=900&q=80" },
      { name: "Millennium Place Marina", area: "Dubai Marina", rating: 4, net: 520, image: "https://images.unsplash.com/photo-1540541338287-41700207dee6?auto=format&fit=crop&w=900&q=80" },
      { name: "Sofitel Dubai The Palm", area: "Palm Jumeirah", rating: 5, net: 940, image: "https://images.unsplash.com/photo-1549294413-26f195200c16?auto=format&fit=crop&w=900&q=80" },
    ],
  },
  {
    slug: "singapore",
    name: "Singapore",
    tagline: "Urban holidays, Sentosa add-ons, shopping, and family packages.",
    image: "https://images.unsplash.com/photo-1525625293386-3f8f99389edd?auto=format&fit=crop&w=1600&q=85",
    places: [
      { name: "Gardens by the Bay", note: "Supertrees, flower dome, cloud forest, and evening light shows." },
      { name: "Sentosa Island", note: "Beaches, Universal Studios, cable car, and family activities." },
      { name: "Marina Bay", note: "Promenade, shopping, skyline, and dining." },
      { name: "Orchard Road", note: "Shopping, cafes, and city hotels." },
    ],
    hotels: [
      { name: "Hotel Boss Singapore", area: "Kampong Glam", rating: 4, net: 610, image: "https://images.unsplash.com/photo-1562790351-d273a961e0e9?auto=format&fit=crop&w=900&q=80" },
      { name: "Village Hotel Sentosa", area: "Sentosa", rating: 4, net: 880, image: "https://images.unsplash.com/photo-1596394516093-501ba68a0ba6?auto=format&fit=crop&w=900&q=80" },
      { name: "Carlton Hotel Singapore", area: "City Hall", rating: 5, net: 970, image: "https://images.unsplash.com/photo-1445019980597-93fa8acb246c?auto=format&fit=crop&w=900&q=80" },
    ],
  },
  {
    slug: "malaysia",
    name: "Malaysia",
    tagline: "Kuala Lumpur, Langkawi, Genting, Penang, and beach stays.",
    image: "https://images.unsplash.com/photo-1596422846543-75c6fc197f07?auto=format&fit=crop&w=1600&q=85",
    places: [
      { name: "Petronas Twin Towers", note: "Kuala Lumpur skyline, shopping, and evening city tours." },
      { name: "Genting Highlands", note: "Theme parks, mountain air, and resort stays." },
      { name: "Langkawi", note: "Beaches, island hopping, cable car, and honeymoon stays." },
      { name: "Penang", note: "Street food, heritage lanes, and coastal hotels." },
    ],
    hotels: [
      { name: "Traders Hotel Kuala Lumpur", area: "KLCC", rating: 5, net: 520, image: "https://images.unsplash.com/photo-1541971875076-8f970d573be6?auto=format&fit=crop&w=900&q=80" },
      { name: "Berjaya Langkawi Resort", area: "Langkawi", rating: 5, net: 650, image: "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?auto=format&fit=crop&w=900&q=80" },
      { name: "Hotel Stripes Kuala Lumpur", area: "Chow Kit", rating: 5, net: 410, image: "https://images.unsplash.com/photo-1554647286-f365d7defc2d?auto=format&fit=crop&w=900&q=80" },
    ],
  },
  {
    slug: "bali",
    name: "Bali",
    tagline: "Honeymoon villas, Ubud retreats, beaches, and private tours.",
    image: "https://images.unsplash.com/photo-1537996194471-e657df975ab4?auto=format&fit=crop&w=1600&q=85",
    places: [
      { name: "Ubud", note: "Rice terraces, temples, villas, cafes, and wellness retreats." },
      { name: "Nusa Dua", note: "Beach resorts, water sports, and family-friendly stays." },
      { name: "Uluwatu", note: "Cliff views, temple sunsets, and beach clubs." },
      { name: "Kintamani", note: "Volcano views, coffee stops, and scenic drives." },
    ],
    hotels: [
      { name: "The Sankara Resort Ubud", area: "Ubud", rating: 4, net: 460, image: "https://images.unsplash.com/photo-1602002418082-a4443e081dd1?auto=format&fit=crop&w=900&q=80" },
      { name: "Grand Mirage Resort Bali", area: "Nusa Dua", rating: 5, net: 730, image: "https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?auto=format&fit=crop&w=900&q=80" },
      { name: "Anantara Uluwatu Bali Resort", area: "Uluwatu", rating: 5, net: 1180, image: "https://images.unsplash.com/photo-1559599189-fe84dea4eb79?auto=format&fit=crop&w=900&q=80" },
    ],
  },
  {
    slug: "thailand",
    name: "Thailand",
    tagline: "Bangkok, Phuket, Krabi, Pattaya, islands, and nightlife.",
    image: "https://images.unsplash.com/photo-1508009603885-50cf7c579365?auto=format&fit=crop&w=1600&q=85",
    places: [
      { name: "Bangkok", note: "Temples, malls, food tours, river cruises, and nightlife." },
      { name: "Phuket", note: "Beach resorts, island hopping, shows, and private transfers." },
      { name: "Krabi", note: "Limestone cliffs, Railay Beach, and long-tail boat tours." },
      { name: "Pattaya", note: "Family attractions, beach stays, and entertainment." },
    ],
    hotels: [
      { name: "Mandarin Hotel Bangkok", area: "Bangkok", rating: 4, net: 360, image: "https://images.unsplash.com/photo-1551776235-dde6d482980b?auto=format&fit=crop&w=900&q=80" },
      { name: "Deevana Patong Resort", area: "Phuket", rating: 4, net: 390, image: "https://images.unsplash.com/photo-1563911302283-d2bc129e7570?auto=format&fit=crop&w=900&q=80" },
      { name: "Dusit Thani Krabi Beach Resort", area: "Krabi", rating: 5, net: 710, image: "https://images.unsplash.com/photo-1529290130-4ca3753253ae?auto=format&fit=crop&w=900&q=80" },
    ],
  },
];
